---
# incendiary-ferret-ambassador-test-ready
apiVersion: v1
kind: Pod
metadata:
  name: "incendiary-ferret-ambassador-test-ready"
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['incendiary-ferret-ambassador:80/ambassador/v0/check_ready']
  restartPolicy: Never
MANIFEST:

---
# Source: ambassador/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incendiary-ferret-ambassador
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubernetesserviceresolvers.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: kubernetesserviceresolvers
    singular: kubernetesserviceresolver
    kind: KubernetesServiceResolver
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authservices.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: authservices
    singular: authservice
    kind: AuthService
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consulresolvers.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: consulresolvers
    singular: consulresolver
    kind: ConsulResolver
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubernetesendpointresolvers.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: kubernetesendpointresolvers
    singular: kubernetesendpointresolver
    kind: KubernetesEndpointResolver
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mappings.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: mappings
    singular: mapping
    kind: Mapping
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: modules.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: modules
    singular: module
    kind: Module
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ratelimitservices.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: ratelimitservices
    singular: ratelimitservice
    kind: RateLimitService
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tlscontexts.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: tlscontexts
    singular: tlscontext
    kind: TLSContext
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tracingservices.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: tracingservices
    singular: tracingservice
    kind: TracingService
---
# Source: ambassador/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tcpmappings.getambassador.io
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller

  annotations:
    "helm.sh/resource-policy": keep

spec:
  group: getambassador.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: tcpmappings
    singular: tcpmapping
    kind: TCPMapping
---
# Source: ambassador/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: incendiary-ferret-ambassador
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
rules:
  - apiGroups: [""]
    resources:
    - namespaces
    - services
    - secrets
    - endpoints
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "getambassador.io" ]
    resources: [ "*" ]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: ["get", "list", "watch"]
---
# Source: ambassador/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: incendiary-ferret-ambassador
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incendiary-ferret-ambassador
subjects:
  - name: incendiary-ferret-ambassador
    namespace: "default"
    kind: ServiceAccount
---
# Source: ambassador/templates/admin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: incendiary-ferret-ambassador-admins
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8877
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/instance: incendiary-ferret
---
# Source: ambassador/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: incendiary-ferret-ambassador
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        service_port: 8080

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/instance: incendiary-ferret
---
# Source: ambassador/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incendiary-ferret-ambassador
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-2.8.1
    app.kubernetes.io/instance: incendiary-ferret
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: ambassador
      app.kubernetes.io/instance: incendiary-ferret
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ambassador
        app.kubernetes.io/instance: incendiary-ferret
      annotations:
        checksum/config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      securityContext:
        runAsUser: 8888

      serviceAccountName: incendiary-ferret-ambassador
      volumes:
      containers:
        - name: ambassador
          image: "quay.io/datawire/ambassador:0.71.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: admin
              containerPort: 8877
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: AMBASSADOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 3
          volumeMounts:
          resources:
            {}

      imagePullSecrets:
        []

      dnsPolicy: ClusterFirst
      hostNetwork: false
