---
# schedules.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schedules.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: schedules
    kind: Schedule
---
# downloadrequests.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: downloadrequests.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: downloadrequests
    kind: DownloadRequest
---
# deletebackuprequests.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deletebackuprequests.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: deletebackuprequests
    kind: DeleteBackupRequest
---
# backups.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: backups
    kind: Backup
---
# volumesnapshotlocations.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: volumesnapshotlocations
    kind: VolumeSnapshotLocation
---
# restores.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: restores
    kind: Restore
---
# backupstoragelocations.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: backupstoragelocations
    kind: BackupStorageLocation
---
# podvolumebackups.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podvolumebackups.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: podvolumebackups
    kind: PodVolumeBackup
---
# resticrepositories.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resticrepositories.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: resticrepositories
    kind: ResticRepository
---
# podvolumerestores.ark.heptio.com
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podvolumerestores.ark.heptio.com
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ark.heptio.com
  version: v1
  scope: Namespaced
  names:
    plural: podvolumerestores
    kind: PodVolumeRestore
MANIFEST:

---
# Source: ark/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wistful-ferret-ark
  labels:
    app: ark
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
type: Opaque
data:
---
# Source: ark/templates/serviceaccount-server.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wistful-ferret-ark-server
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
---
# Source: ark/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wistful-ferret-ark-server
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
subjects:
  - kind: ServiceAccount
    namespace: default
    name: wistful-ferret-ark-server
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: ark/templates/backupstoragelocation.yaml
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  labels:
    chart: ark-4.2.2
    heritage: Tiller
    release: wistful-ferret
    app: ark
spec:
  provider:
  objectStorage:
    bucket:
WARNING: Validation skipped because CRDs are not installed
