---
# Source: elastalert/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: truculent-greyhound-elastalert-config
  labels:
    app: elastalert
    chart: elastalert-1.0.0
    release: truculent-greyhound
    heritage: Tiller
data:
  elastalert_config: |-
    ---
    rules_folder: /opt/rules
    scan_subdirectories: false
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host:
    es_port: 80
    writeback_index: elastalert_status
    use_ssl: False
    verify_certs: True
    alert_time_limit:
      minutes: 2880
---
# Source: elastalert/templates/rules.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: truculent-greyhound-elastalert-rules
  labels:
    app: elastalert
    chart: elastalert-1.0.0
    release: truculent-greyhound
    heritage: Tiller
data:
