---
# Source: heartbeat/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: factual-chimp-heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.2.0
    release: factual-chimp
    heritage: Tiller
type: Opaque
data:
  heartbeat.yml: ICAgIGhlYXJ0YmVhdC5tb25pdG9yczoKICAgIC0gaG9zdHM6CiAgICAgIC0gbG9jYWxob3N0CiAgICAgIGlwdjQ6IHRydWUKICAgICAgc2NoZWR1bGU6ICcqLzUgKiAqICogKiAqIConCiAgICAgIHRpbWVvdXQ6IDE2cwogICAgICB0eXBlOiBpY21wCiAgICAgIHdhaXQ6IDFzCiAgICBvdXRwdXQuZmlsZToKICAgICAgZmlsZW5hbWU6IGhlYXJ0YmVhdAogICAgICBudW1iZXJfb2ZfZmlsZXM6IDUKICAgICAgcGF0aDogL3Vzci9zaGFyZS9oZWFydGJlYXQvZGF0YQogICAgICByb3RhdGVfZXZlcnlfa2I6IDEwMDAwCiAgICBwcm9jZXNzb3JzOgogICAgLSBhZGRfY2xvdWRfbWV0YWRhdGE6IG51bGwKICAgIA==
---
# Source: heartbeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: factual-chimp-heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.2.0
    release: factual-chimp
    heritage: Tiller
---
# Source: heartbeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: factual-chimp-heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.2.0
    release: factual-chimp
    heritage: Tiller
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
# Source: heartbeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: factual-chimp-heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.2.0
    release: factual-chimp
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: factual-chimp-heartbeat
subjects:
- kind: ServiceAccount
  name: factual-chimp-heartbeat
  namespace: default
---
# Source: heartbeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: factual-chimp-heartbeat
  labels:
    app: heartbeat
    chart: heartbeat-1.2.0
    release: factual-chimp
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: heartbeat
      release: factual-chimp
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: heartbeat
        release: factual-chimp
      annotations:
        checksum/secret: a78b7094af586379a27280677499106ea388252a7ef1dd2f386c40e21fd7b51e
    spec:
      containers:
      - name: heartbeat
        image: "docker.elastic.co/beats/heartbeat:6.7.0"
        imagePullPolicy: IfNotPresent
        args:
        - "-e"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          runAsUser: 0
        resources:
          {}
          
        volumeMounts:
        - name: heartbeat-config
          mountPath: /usr/share/heartbeat/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
        - name: data
          mountPath: /usr/share/heartbeat/data
      volumes:
      - name: heartbeat-config
        secret:
          secretName: factual-chimp-heartbeat
      - name: data
        hostPath:
          path: /var/lib/heartbeat
          type: DirectoryOrCreate
      terminationGracePeriodSeconds: 60
      serviceAccountName: factual-chimp-heartbeat
