---
# Source: ignite/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fun-echidna-ignite-configmap
data:
  ignite-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->

    <!--
        Configuration example with Kubernetes IP finder and Ignite persistence enabled.
        WAL files and database files are stored in separate disk drives.
    -->
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans.xsd">

        <bean class="org.apache.ignite.configuration.IgniteConfiguration">

            <property name="peerClassLoadingEnabled" value="false"/>
            <!-- Explicitly configure TCP discovery SPI to provide list of initial nodes. -->
            <property name="discoverySpi">
                <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                        <!--
                            Enables Kubernetes IP finder and setting custom namespace and service names.
                        -->
                        <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                            <property name="namespace" value="default"/>
                            <property name="serviceName" value="fun-echidna-ignite"/>
                        </bean>
                    </property>
                </bean>
            </property>
        </bean>
    </beans>
---
# Source: ignite/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fun-echidna-ignite
---
# Source: ignite/templates/account-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fun-echidna-ignite
rules:
- apiGroups:
  - ""
  resources: # Here are resources you can access
  - pods
  - endpoints
  verbs: # That is what you can do with them
  - get
  - list
  - watch
---
# Source: ignite/templates/role-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fun-echidna-ignite
roleRef:
  kind: ClusterRole
  name: fun-echidna-ignite
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fun-echidna-ignite
  namespace: default
---
# Source: ignite/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: fun-echidna-ignite
  labels:
    app: fun-echidna-ignite
spec:
  ports:
    - name: jdbc
      port: 11211
      targetPort: 11211
    - name: spi-communication
      port: 47100
      targetPort: 47100
    - name: spi-discovery
      port: 47500
      targetPort: 47500
    - name: jmx
      port: 49112
      targetPort: 49112
    - name: sql
      port: 10800
      targetPort: 10800
    - name: rest
      port: 8080
      targetPort: 8080
    - name: thin-clients
      port: 10900
      targetPort: 10900
  clusterIP: None
  selector:
    app: fun-echidna-ignite
---
# Source: ignite/templates/stateful-set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fun-echidna-ignite
  labels:
    app.kubernetes.io/name: ignite
    helm.sh/chart: ignite-1.0.0
    app.kubernetes.io/instance: fun-echidna
    app.kubernetes.io/managed-by: Tiller
spec:
  selector:
    matchLabels:
      app: fun-echidna-ignite
  serviceName: fun-echidna-ignite
  replicas: 2
  template:
    metadata:
      labels:
        app: fun-echidna-ignite
    spec:
      serviceAccountName: fun-echidna-ignite
      volumes:
        - name: config-volume
          configMap:
            name: fun-echidna-ignite-configmap
            items:
            - key: ignite-config.xml
              path: default-config.xml
      containers:
      - name: ignite
        image: "apacheignite/ignite:2.7.0"
        resources:
          {}
          
        env:
        - name: "IGNITE_QUIET"
          value: "false"
        - name: "JVM_OPTS"
          value: "-Djava.net.preferIPv4Stack=true"
        - name: "OPTION_LIBS"
          value: "ignite-kubernetes,ignite-rest-http"
        ports:
        - containerPort: 11211 # JDBC port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 8080 # REST port number.
        - containerPort: 10900 #Thin clients port number.
        volumeMounts:
        - name: config-volume
          mountPath: /opt/ignite/apache-ignite-fabric/config
  volumeClaimTemplates:
